[2022-10-24 09:44:27,240] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.mapping_interactions scheduled__2022-10-23T00:00:00+00:00 [queued]>
[2022-10-24 09:44:27,245] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.mapping_interactions scheduled__2022-10-23T00:00:00+00:00 [queued]>
[2022-10-24 09:44:27,245] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-24 09:44:27,245] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-10-24 09:44:27,245] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-24 09:44:27,253] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): mapping_interactions> on 2022-10-23 00:00:00+00:00
[2022-10-24 09:44:27,257] {standard_task_runner.py:52} INFO - Started process 3481 to run task
[2022-10-24 09:44:27,261] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline', 'mapping_interactions', 'scheduled__2022-10-23T00:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/.ipynb_checkpoints/lead_scoring_data_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpk7crr4y_', '--error-file', '/tmp/tmp2y4u6w_i']
[2022-10-24 09:44:27,262] {standard_task_runner.py:80} INFO - Job 227: Subtask mapping_interactions
[2022-10-24 09:44:27,305] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline.mapping_interactions scheduled__2022-10-23T00:00:00+00:00 [running]> on host 0307537c0a24
[2022-10-24 09:44:27,356] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline
AIRFLOW_CTX_TASK_ID=mapping_interactions
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-23T00:00:00+00:00
[2022-10-24 09:44:27,357] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: interactions_mapping() missing 1 required positional argument: 'interaction_mapping_file'
[2022-10-24 09:44:27,360] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_Scoring_Data_Engineering_Pipeline, task_id=mapping_interactions, execution_date=20221023T000000, start_date=20221024T094427, end_date=20221024T094427
[2022-10-24 09:44:27,368] {standard_task_runner.py:92} ERROR - Failed to execute job 227 for task mapping_interactions (interactions_mapping() missing 1 required positional argument: 'interaction_mapping_file'; 3481)
[2022-10-24 09:44:27,390] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-24 09:44:27,415] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
